import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import ReactQueryClient from "./ReactQueryClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased p-4 `}>
        <ReactQueryClient>
          <Theme accentColor="violet">
            <Container>
              <AuthProvider>
                <NavBar />
                <main>{children}</main>
              </AuthProvider>
            </Container>
          </Theme>
        </ReactQueryClient>
      </body>
    </html>
  );
}
